### ISSUE TITLE
Form designer breaking with Dapplo.Jira installed

### ISSUE THREAD

**Issue by richardwarriner** [dapplo/Dapplo.Jira#71] opened 2022-02-11 15:09 UTC
Running VS 17.0.6

Create a new Windows Forms .net6 app and add some buttons etc. All if ok

Add nuget of Dapplo.Jira 1.1.42 and then go back to the form. You now cannot click on any control of it you add more controls to the form they just appear at the bottom in the area for non UI controls

Am I doing something wrong here?

![2022-02-11 15_06_43-Window](https://user-images.githubusercontent.com/1065030/153616416-488bb31b-9b13-4c8d-bc07-2e88f98149e8.jpg)

**Comment by Lakritzator** [comment] 2022-02-12 10:40
What magic is that... I never heard about such a thing, and I do no see a direct reason for something like that.

**Comment by richardwarriner** [comment] 2022-02-12 10:47
I know - it's crazy isn't it. Can you reproduce it on your system? I am just concerned its something I am doing

**Comment by Lakritzator** [comment] 2022-02-12 11:00
My first instinct wasthat it might be a bug in 17.0.6 with the forms designer and might also happen with other nugets.

So I checked it out as I wanted to know if this is due to my Dapplo.Jira package, the [Dapplo.HttpExtensions](https://www.nuget.org/packages/Dapplo.HttpExtensions) or [Dapplo.HttpExtensions.JsonNet](https://www.nuget.org/packages/Dapplo.HttpExtensions.JsonNet/)

It seems to be something in the https://www.nuget.org/packages/Dapplo.HttpExtensions that is (also) triggering the behavior, that is a HTTP client and should not cause such things... For now I first want to spend some time with my family, I'll check tonight.

**Comment by Lakritzator** [comment] 2022-02-12 11:01
P.S. if it wasn't clear, yeah I can reproduce it!!

**Comment by richardwarriner** [comment] 2022-02-12 11:01
No worries - its not urgent :)

**Comment by Lakritzator** [comment] 2022-02-12 21:36
I believe it's due to Dapplo.Log being at an older level. It took me all night to find something that might cause it, now my time-boxing is over. But I managed to update Dapplo.Log to an already available 1.4.1 and the problem seemed to be away.

If you are behind this PC before I can provide a different solution, maybe you can try to install Dapplo.Log 1.4.1 directly to see if this helps.

**Comment by Lakritzator** [comment] 2022-02-13 17:17
I'll update Dapplo.Jira so it uses 1.4.1, so others don't get the same issue and you don't need to do this manually.
I didn't update Dapplo.Log before (1.4.1 was already longer out), as there wasn't a big need, but I guess there is now.

Thanks for reporting, closing this as anything newer than 1.1.42 (which will come later today / tomorrow) should fix it.

**Closed by Lakritzator** 2022-02-13 17:17 UTC
Labels: bug, help wanted

**Comment by Lakritzator** [comment] 2022-02-13 22:31
Should be fixed with [1.1.43](https://www.nuget.org/packages/Dapplo.Jira/1.1.43) and later.
